### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\user\Downloads\hypixel-auction-bot-master\bot.py", line 14, in <module>     import nbt.nbt as nbt ModuleNotFoundError: No module named 'nbt'

### ISSUE THREAD

**Issue by Crazygamer212** [crepppy/hypixel-auction-bot#1]
Traceback (most recent call last):
  File "C:\Users\user\Downloads\hypixel-auction-bot-master\bot.py", line 14, in <module>
    import nbt.nbt as nbt
ModuleNotFoundError: No module named 'nbt'

i get this error while runing in 3.11

**Comment by jackchapm** [comment]
Did you install the dependencies from `requirements.txt`? Either way, this repository is no longer maintained and unlikely to function properly with Skyblocks current API.
